redis_ambassador:
 image: svendowideit/ambassador
 environment:
  - REDIS_PORT_6379_TCP=tcp://107.170.92.137:6379
 expose:
  - "6379"
redis-cli:
 image: relateiq/redis-cli
 links:
  - redis_ambassador:redis
